[build]
  base = "apps/academia-dei-landing"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/@swc/core-linux-x64-gnu/**/*", "!node_modules/@swc/core-linux-x64-musl/**/*"]