[build]
  base = "apps/academia-growth"
  command = "npm install --force && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["!node_modules/@swc/core-linux-x64-gnu/**/*", "!node_modules/@swc/core-linux-x64-musl/**/*"]